// Generated by CoffeeScript 1.4.0
(function() {
  var Mixmaster,
    __slice = [].slice;

  module.exports = Mixmaster = (function() {

    function Mixmaster() {}

    Mixmaster.include = function(mixins) {
      var key, mixin, value, _i, _len, _ref, _results;
      _results = [];
      for (_i = 0, _len = mixins.length; _i < _len; _i++) {
        mixin = mixins[_i];
        _ref = mixin.prototype;
        for (key in _ref) {
          value = _ref[key];
          if (this.prototype[key] != null) {
            if (key === 'constructor') {
              continue;
            }
            console.log("Overwriting " + key + "...");
          }
          this.prototype[key] = value;
        }
        _results.push(this);
      }
      return _results;
    };

    Mixmaster.construct = function() {
      var args, mixin, mixins, object, _i, _len, _results;
      object = arguments[0], mixins = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      _results = [];
      for (_i = 0, _len = mixins.length; _i < _len; _i++) {
        mixin = mixins[_i];
        _results.push(mixin.call.apply(mixin, [object].concat(__slice.call(args))));
      }
      return _results;
    };

    return Mixmaster;

  })();

}).call(this);
